##**Домашнее задание по теме  "Линейная алгебра. Матрицы"**

**Задание:**

Рекомендуем вам выделить 3 академических часа для эффективного обучения.
Домашнее задание доступно по ссылке: https://github.com/Netology-DS/MDS/blob/main/MDS-new/HW_2_upd.ipy.

**Решение:**

**Уровень 1:**


 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [ ]:
import numpy as np

# Создаем матрицу 3*3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Создаем единичную матрицу, размерностью также 3*3
B = np.eye(3)

# Складываем эти матрицы
C = np.add(A, B)

# Создаем новый вектор
D = np.array([1, 2, 3])

# Умножаем матрицу C на вектор D
result = np.dot(C, D)

# Транспонируем матрицу C
AT = np.transpose(C)

# Считаем обратную матрицу к матрице C
try:
    inv_C = np.linalg.inv(C)
except np.linalg.LinAlgError:
    inv_C = None

print("Новая матрица А:")
print(A)

print("\nСумма матриц A и B:")
print(C)

print("\nУмножение матрицы C на вектор D:")
print(result)

print("\nТранспонированная матрица C:")
print(AT)

if inv_C is not None:
    print("\nОбратная матрица к матрице C:")
    print(inv_C)
else:
    print("\nОбратная матрица к матрице C не существует.")


Новая матрица А:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Сумма матриц A и B:
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]

Умножение матрицы C на вектор D:
[15. 34. 53.]

Транспонированная матрица C:
[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]

Обратная матрица к матрице C:
[[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01 -2.33146835e-16]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]


**Уровень 2:**

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
m = np.array([[2, 2],
              [1, 3]])

# Вычислим собственные значения
eigenvalues = np.linalg.eigvals(m)

# Вычислим собственные векторы
eigenvectors = np.linalg.eig(m)[1]

# Выведем результат
print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)


Собственные значения:
[1. 4.]

Собственные векторы:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
import numpy as np
import random

# Генерируем матрицу 3*3
while True:
    m = np.zeros((3, 3))

    # Генерируем случайные ненулевые элементы матрицы
    for i in range(3):
        non_zero_elements = random.sample(range(1, 10), 3)
        m[i] = non_zero_elements

    # Проверяем условие, что определитель матрицы равен 1
    if np.linalg.det(m) == 1:
        break

print("Сгенерированная матрица:")
print(m)


Сгенерированная матрица:
[[8. 6. 3.]
 [8. 7. 3.]
 [5. 4. 2.]]


In [ ]:
# Проверим определитель сгенерированной матрицы
det = np.linalg.det(m)

print(det)

1.0
